/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Entity.Module;
import Tools.Tools;
import static Tools.Tools.Message;
import static db.go.TableColumnCount;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.event.TableColumnModelEvent;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdelatif Hamdi
 */
public class Bulletin extends javax.swing.JFrame {

    /**
     * Creates new form Bulletin
     */
    public Bulletin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Ann = new com.toedter.calendar.JYearChooser();
        Sem = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        ComNum = new controls.JMyCombo();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblNote = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new controls.JMyBottom();
        jMyBottom1 = new controls.JMyBottom();
        jMyBottom4 = new controls.JMyBottom();
        jMyBottom5 = new controls.JMyBottom();
        txtRes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        remarque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numéro :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Sem.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Semestre :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        ComNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComNumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Année :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TblNote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TblNote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Numéro", "Module", "Semestre", "Année", "Niveau", "TD", "TP", "Examen", "NoteF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblNote.setRowHeight(30);
        TblNote.setRowMargin(10);
        TblNote.setSelectionBackground(new java.awt.Color(70, 130, 180));
        TblNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblNoteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblNote);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setText("relevé des notes");

        btnBack.setText("Retoure");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jMyBottom1.setText("Imprimer");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });

        jMyBottom4.setText("Afficher");
        jMyBottom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom4ActionPerformed(evt);
            }
        });

        jMyBottom5.setText("Calculer");
        jMyBottom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom5ActionPerformed(evt);
            }
        });

        txtRes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRes.setText("0.00");
        txtRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("La Note :");

        remarque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remarque.setText("La moyenne n'a pas encore calculé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ComNum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarque)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jMyBottom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jMyBottom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(316, 316, 316))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(915, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jMyBottom1, jMyBottom4, jMyBottom5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ComNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Ann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMyBottom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBottom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRes)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(remarque, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(509, 509, 509)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComNumActionPerformed

    private void TblNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblNoteMouseClicked
        
    }//GEN-LAST:event_TblNoteMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnBackActionPerformed
Entity.Etudiant e = new Entity.Etudiant();
    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
        // TODO add your handling code here:
        try {
            String s = e.getNameByValue(ComNum.getSelectedItem().toString());
            MessageFormat header = new MessageFormat("L'étudiant : "+s+" "+ComNum.getSelectedItem().toString());
            MessageFormat footer = new MessageFormat("La moyenne : "+txtRes.getText()+"  "+remarque.getText());
            TblNote.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException exs) {
            Message(exs.getMessage());
        }
    }//GEN-LAST:event_jMyBottom1ActionPerformed
    private void jMyBottom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom4ActionPerformed
        // TODO add your handling code here:
        TblNote.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TblNote.getTableHeader().setOpaque(false);
TblNote.getTableHeader().setBackground(new Color(32, 136, 203));
TblNote.getTableHeader().setForeground(new Color(255, 255, 255));
        Entity.Note n = new Entity.Note();
        String strselect = "select * from NoteWithName where NumE='"+ComNum.getSelectedItem().toString()
        +"' and Semestre="+Sem.getValue()+
        " and Année="+Ann.getValue();
        n.getCustomRows(strselect, TblNote);
        TblNote.removeColumn(TblNote.getColumn("Niveau"));
        TblNote.removeColumn(TblNote.getColumn("Semestre"));
        TblNote.removeColumn(TblNote.getColumn("Année"));
        TblNote.removeColumn(TblNote.getColumn("Nom"));
        TblNote.removeColumn(TblNote.getColumn("Numéro"));
        
    }//GEN-LAST:event_jMyBottom4ActionPerformed

    private void txtResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResActionPerformed
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        db.go.MyfillCombo("Etudiant", "NumE", ComNum,TableColumnCount("Etudiant"));    }//GEN-LAST:event_formWindowOpened
Entity.Module m = new Module();
    private void jMyBottom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom5ActionPerformed
        // TODO add your handling code here:
        double resultat=0; int CoefCount=0;
        for (int i=0;i<TblNote.getRowCount();i++){
        int coef = m.getCoefByName((String) TblNote.getValueAt(i, 0));
        CoefCount+=coef;
        double NoteF = Double.parseDouble((String)TblNote.getValueAt(i, 4));
        resultat+=NoteF*coef;
        
        }
        resultat/=CoefCount;
        double d = (double) Math.round(resultat * 100) / 100;
        if (resultat<10){  
            remarque.setText("rater malheureusements..");
            remarque.setForeground(Color.red);}
        else {
            remarque.setText("réussi félicitations !");
            remarque.setForeground(Color.GREEN);}
        txtRes.setText(String.valueOf(d));
        
    }//GEN-LAST:event_jMyBottom5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bulletin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bulletin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bulletin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bulletin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bulletin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser Ann;
    private controls.JMyCombo ComNum;
    private javax.swing.JSpinner Sem;
    private javax.swing.JTable TblNote;
    private controls.JMyBottom btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private controls.JMyBottom jMyBottom1;
    private controls.JMyBottom jMyBottom4;
    private controls.JMyBottom jMyBottom5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remarque;
    private javax.swing.JTextField txtRes;
    // End of variables declaration//GEN-END:variables
}
