/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Tools.Tools;
import static Tools.Tools.Message;
import Tools.Tools.Table;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdelatif Hamdi
 */
public class Etudiant extends javax.swing.JFrame {

    /**
     * Creates new form Employe
     */
    public Etudiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNumE = new controls.JTextBox(20);
        TextNomE = new controls.JTextBox(20);
        Textaddress = new controls.JTextBox(20);
        TextEmail = new controls.JTextBox(20);
        TextNaissance = new com.toedter.calendar.JDateChooser();
        btnModifier = new controls.JMyBottom();
        btnAjouter = new controls.JMyBottom();
        btnEffacer = new controls.JMyBottom();
        btnTrouver = new controls.JMyBottom();
        btnTout = new controls.JMyBottom();
        btnSup = new controls.JMyBottom();
        btnBack = new controls.JMyBottom();
        jLabel9 = new javax.swing.JLabel();
        RdoNumE = new javax.swing.JRadioButton();
        RdoNomE = new javax.swing.JRadioButton();
        RdoNaissance = new javax.swing.JRadioButton();
        RdoAddress = new javax.swing.JRadioButton();
        RdoNum = new javax.swing.JRadioButton();
        RdoEmail = new javax.swing.JRadioButton();
        RdoSpécialité = new javax.swing.JRadioButton();
        TextRecherche = new controls.JTextBox(30);
        btnRecherche = new controls.JMyBottom();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEtudiant = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TextNumTélé = new controls.JTextBox(20);
        jLabel11 = new javax.swing.JLabel();
        TextSpécialité = new controls.JTextBox(20);
        jLabel12 = new javax.swing.JLabel();
        Choiser = new javax.swing.JButton();
        ImageShower = new javax.swing.JLabel();
        jMyBottom1 = new controls.JMyBottom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setText("Forme Etudiant");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numéro :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom :");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("D.Naissance :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TextNumE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TextNomE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Textaddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TextEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnTrouver.setText("Trouver");
        btnTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverActionPerformed(evt);
            }
        });

        btnTout.setText("Tout");
        btnTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutActionPerformed(evt);
            }
        });

        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnBack.setText("Retoure");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rechercher avec :");

        RdoNumE.setBackground(new java.awt.Color(255, 255, 255));
        RdoNumE.setSelected(true);
        RdoNumE.setText("Numéro");
        RdoNumE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoNumEActionPerformed(evt);
            }
        });

        RdoNomE.setBackground(new java.awt.Color(255, 255, 255));
        RdoNomE.setText("Nom");

        RdoNaissance.setBackground(new java.awt.Color(255, 255, 255));
        RdoNaissance.setText("Naissance");
        RdoNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoNaissanceActionPerformed(evt);
            }
        });

        RdoAddress.setBackground(new java.awt.Color(255, 255, 255));
        RdoAddress.setText("Address");
        RdoAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoAddressActionPerformed(evt);
            }
        });

        RdoNum.setBackground(new java.awt.Color(255, 255, 255));
        RdoNum.setText("Num");

        RdoEmail.setBackground(new java.awt.Color(255, 255, 255));
        RdoEmail.setText("Email");

        RdoSpécialité.setBackground(new java.awt.Color(255, 255, 255));
        RdoSpécialité.setText("Spécialité");

        TextRecherche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        TblEtudiant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TblEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Naissance", "Address", "Num", "Email", "Spécialtité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblEtudiant.setRowHeight(30);
        TblEtudiant.setRowMargin(10);
        TblEtudiant.setSelectionBackground(new java.awt.Color(70, 130, 180));
        TblEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEtudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblEtudiant);
        if (TblEtudiant.getColumnModel().getColumnCount() > 0) {
            TblEtudiant.getColumnModel().getColumn(0).setHeaderValue("Numéro");
            TblEtudiant.getColumnModel().getColumn(1).setHeaderValue("Nom");
            TblEtudiant.getColumnModel().getColumn(2).setHeaderValue("Naissance");
            TblEtudiant.getColumnModel().getColumn(3).setHeaderValue("Address");
            TblEtudiant.getColumnModel().getColumn(4).setHeaderValue("Num");
            TblEtudiant.getColumnModel().getColumn(5).setHeaderValue("Email");
            TblEtudiant.getColumnModel().getColumn(6).setHeaderValue("Spécialtité");
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Téléphone :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TextNumTélé.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Spécialité :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TextSpécialité.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Photo :");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Choiser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Choiser.setText("Choiser");
        Choiser.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        Choiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiserActionPerformed(evt);
            }
        });

        ImageShower.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 153)));

        jMyBottom1.setText("Imprimer");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(Choiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TextNumTélé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Textaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNomE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNumE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSpécialité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageShower, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RdoNumE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RdoNomE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RdoNaissance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoSpécialité))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnEffacer, btnModifier, btnSup, btnTout, btnTrouver, jMyBottom1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Choiser, TextNaissance});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImageShower, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextNumE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNomE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TextNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TextSpécialité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Choiser)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextNumTélé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(46, 46, 46)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RdoNumE)
                                    .addComponent(RdoNomE)
                                    .addComponent(RdoNaissance)
                                    .addComponent(RdoAddress)
                                    .addComponent(RdoNum)
                                    .addComponent(RdoEmail)
                                    .addComponent(RdoSpécialité))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        setValues();
    e.update();
    Clear();
    e.getAllRows(TblEtudiant);

    }//GEN-LAST:event_btnModifierActionPerformed
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
setValues();
    e.add();
    Clear();
    e.getAllRows(TblEtudiant);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverActionPerformed
String strNumE = (String) Tools.InputBox("Entrer le Numéro de d'Etudiant ...");
    int NumE = Integer.parseInt(strNumE);
    e.setNumE(NumE);
    e.getOneRow(TblEtudiant);
    Image i =  e.getPhotoByNumE(NumE+"");
      Image newi = i.getScaledInstance(108, 125, Image.SCALE_AREA_AVERAGING);
      ImageIcon az = new ImageIcon(newi);
    
         ImageShower.setIcon(az);
    
    
    }//GEN-LAST:event_btnTrouverActionPerformed

    private void btnToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutActionPerformed
        // TODO add your handling code here:
        e.getAllRows(TblEtudiant);
    }//GEN-LAST:event_btnToutActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
    setValues();
    e.delete();
    Clear();
    e.getAllRows(TblEtudiant);
    }//GEN-LAST:event_btnSupActionPerformed
    private void Clear(){
    Tools.ClearTexts(this);
    TextNumE.setText(db.go.getAutoNumber("Etudiant", "NumE"));
            ImageShower.setIcon(null);
    btnAjouter.setEnabled(true);
    btnModifier.setEnabled(false);
    btnSup.setEnabled(false);
    TextNomE.requestFocus();
    
    
    
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.dispose();
Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnBackActionPerformed

    private void RdoNumEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoNumEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoNumEActionPerformed

    private void RdoAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoAddressActionPerformed
    Entity.Etudiant e = new Entity.Etudiant();
    private void setValues(){
    e.setNumE(Integer.parseInt(TextNumE.getText()));
    e.setNomE(TextNomE.getText());
    e.setAddress(Textaddress.getText());
    e.setEmail(TextEmail.getText());
    e.setNumTélé(TextNumTélé.getText());
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    e.setDateN(String.valueOf(s.format(TextNaissance.getDate())));
    e.setSpécialité(TextSpécialité.getText());
    
    }
          
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnGrp.add(RdoNaissance);
        btnGrp.add(RdoNum);
        btnGrp.add(RdoNomE);
        btnGrp.add(RdoAddress);
        btnGrp.add(RdoNumE);
        btnGrp.add(RdoSpécialité);
        btnGrp.add(RdoEmail);
        e.getAllRows(TblEtudiant);
        Clear();
        TblEtudiant.getTableHeader().setReorderingAllowed(false);
        TblEtudiant.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TblEtudiant.getTableHeader().setOpaque(false);
TblEtudiant.getTableHeader().setBackground(new Color(32, 136, 203));
TblEtudiant.getTableHeader().setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened
    private void TblEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEtudiantMouseClicked
        // TODO add your handling code here:
                     try{
         int row = TblEtudiant.getSelectedRow();
         String NumE = TblEtudiant.getValueAt(row, 0).toString();
         String NomE = TblEtudiant.getValueAt(row, 1).toString();
         String DateN = TblEtudiant.getValueAt(row, 2).toString();
         String Address = TblEtudiant.getValueAt(row, 3).toString();
         String NumTélé = TblEtudiant.getValueAt(row, 4).toString();
         String Email = TblEtudiant.getValueAt(row, 5).toString();
         String Spécialité = TblEtudiant.getValueAt(row, 6).toString();
         Image i =  e.getPhotoByNumE(NumE);
      Image newi = i.getScaledInstance(108, 125, Image.SCALE_AREA_AVERAGING);
      ImageIcon az = new ImageIcon(newi);  
         ImageShower.setIcon(az);
         TextNumE.setText(NumE);
         TextNomE.setText(NomE);
         Textaddress.setText(Address);
         TextEmail.setText(Email);
         TextSpécialité.setText(Spécialité);
         TextNumTélé.setText(NumTélé);
                      SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
             Date bd = s.parse(DateN);
         TextNaissance.setDate(bd);
         btnAjouter.setEnabled(false);
         btnModifier.setEnabled(true);
         btnSup.setEnabled(true);
         }catch(ParseException ex)
         {}
    }//GEN-LAST:event_TblEtudiantMouseClicked

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
        String cherche ="select * from Etud_Sans_Img where ";
    if (RdoNumE.isSelected()){ cherche+="NumE="+TextRecherche.getText();}
    else if (RdoNomE.isSelected()){ cherche+="NomE='"+TextRecherche.getText()+"'";}
    else if (RdoNaissance.isSelected()) { cherche+="DateN='"+TextRecherche.getText()+"'";}
    else if (RdoAddress.isSelected()){ cherche+="Adresse='"+TextRecherche.getText()+"'";}
    else if (RdoNum.isSelected()){ cherche+="NumTélé='"+TextRecherche.getText()+"'";}
    else if (RdoEmail.isSelected()){ cherche+="Email='"+TextRecherche.getText()+"'";}
    else if (RdoSpécialité.isSelected()){ cherche+="Spécialité='"+TextRecherche.getText()+"'";}
    e.getCustomRows(cherche, TblEtudiant);  
         Image i =  e.getPhotoByNumE((String) TblEtudiant.getValueAt(0, 0));
      Image newi = i.getScaledInstance(108, 125, Image.SCALE_AREA_AVERAGING);
      ImageIcon az = new ImageIcon(newi);  
         ImageShower.setIcon(az);
            
    
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void ChoiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoiserActionPerformed

        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter f = new FileNameExtensionFilter("images ","img","png","jpg");
            fc.setFileFilter(f);
            fc.showDialog(Choiser, "Selection Des Images  " );
            Image img = ImageIO.read(fc.getSelectedFile());
            Image NewImg = img.getScaledInstance(108, 125, Image.SCALE_AREA_AVERAGING );
            ImageIcon I = new ImageIcon(NewImg);
            ImageShower.setIcon(I);
            e.setPhoto(fc.getSelectedFile().getPath());
        } catch (HeadlessException | IOException ex) {
         Message(ex);
        }
    }//GEN-LAST:event_ChoiserActionPerformed

    private void RdoNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoNaissanceActionPerformed

    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat header = new MessageFormat("Rapport des étudiants ");
            MessageFormat footer = new MessageFormat("Page - {0}");
            TblEtudiant.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
         Message(ex.getMessage());
        }
    }//GEN-LAST:event_jMyBottom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choiser;
    private javax.swing.JLabel ImageShower;
    private javax.swing.JRadioButton RdoAddress;
    private javax.swing.JRadioButton RdoEmail;
    private javax.swing.JRadioButton RdoNaissance;
    private javax.swing.JRadioButton RdoNomE;
    private javax.swing.JRadioButton RdoNum;
    private javax.swing.JRadioButton RdoNumE;
    private javax.swing.JRadioButton RdoSpécialité;
    private javax.swing.JTable TblEtudiant;
    private javax.swing.JTextField TextEmail;
    private com.toedter.calendar.JDateChooser TextNaissance;
    private javax.swing.JTextField TextNomE;
    private javax.swing.JTextField TextNumE;
    private javax.swing.JTextField TextNumTélé;
    private javax.swing.JTextField TextRecherche;
    private javax.swing.JTextField TextSpécialité;
    private javax.swing.JTextField Textaddress;
    private controls.JMyBottom btnAjouter;
    private controls.JMyBottom btnBack;
    private controls.JMyBottom btnEffacer;
    private javax.swing.ButtonGroup btnGrp;
    private controls.JMyBottom btnModifier;
    private controls.JMyBottom btnRecherche;
    private controls.JMyBottom btnSup;
    private controls.JMyBottom btnTout;
    private controls.JMyBottom btnTrouver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private controls.JMyBottom jMyBottom1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
