/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Abdelatif Hamdi
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnDept = new controls.JMyBottom();
        jMyBottom1 = new controls.JMyBottom();
        btnExit1 = new controls.JMyBottom();
        BtnDept1 = new controls.JMyBottom();
        BtnDept2 = new controls.JMyBottom();
        BtnDept3 = new controls.JMyBottom();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forme Principle");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(57, 11, 266, 48);

        BtnDept.setText("Etudiants");
        BtnDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeptActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDept);
        BtnDept.setBounds(100, 100, 190, 23);

        jMyBottom1.setText("Modules et Unités");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMyBottom1);
        jMyBottom1.setBounds(100, 140, 190, 23);

        btnExit1.setText("Sortir");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit1);
        btnExit1.setBounds(10, 336, 83, 23);

        BtnDept1.setText("Notes");
        BtnDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDept1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDept1);
        BtnDept1.setBounds(100, 180, 190, 23);

        BtnDept2.setText("Affichage des modules");
        BtnDept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDept2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDept2);
        BtnDept2.setBounds(100, 220, 190, 23);

        BtnDept3.setText("relevé des notes");
        BtnDept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDept3ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDept3);
        BtnDept3.setBounds(100, 260, 190, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeptActionPerformed
        this.dispose();
        Tools.Tools.OpenForm(new forms.Etudiant());
    }//GEN-LAST:event_BtnDeptActionPerformed

    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
        this.dispose();
        Tools.Tools.OpenForm(new forms.Unité());
    }//GEN-LAST:event_jMyBottom1ActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void BtnDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDept1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.Tools.OpenForm(new forms.Note());
    }//GEN-LAST:event_BtnDept1ActionPerformed

    private void BtnDept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDept2ActionPerformed
this.dispose();
        Tools.Tools.OpenForm(new forms.AffMod());    }//GEN-LAST:event_BtnDept2ActionPerformed

    private void BtnDept3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDept3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.Tools.OpenForm(new forms.Bulletin());
    }//GEN-LAST:event_BtnDept3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        try {
            Image img2 = ImageIO.read(Tools.Tools.class.getResource("fond_ecran_hd_tablette_1.jpg"));
            Image newi = img2.getScaledInstance(400, 420, Image.SCALE_AREA_AVERAGING);
      ImageIcon az = new ImageIcon(newi);  
      jLabel3.setIcon(az);
        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBottom BtnDept;
    private controls.JMyBottom BtnDept1;
    private controls.JMyBottom BtnDept2;
    private controls.JMyBottom BtnDept3;
    private controls.JMyBottom btnExit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private controls.JMyBottom jMyBottom1;
    // End of variables declaration//GEN-END:variables
}
