/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Entity.Module;
import static Tools.Tools.Message;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author Abdelatif Hamdi
 */
public class Unité extends javax.swing.JFrame {

    /**
     * Creates new form Département
     */
    public Unité() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextRecherche = new controls.JTextBox(20);
        TextNumU = new controls.JTextBox(20);
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RadBtnNum = new javax.swing.JRadioButton();
        btnTrouver = new controls.JMyBottom();
        RadBtnNom = new javax.swing.JRadioButton();
        btnTout = new controls.JMyBottom();
        RadBtnCoefU = new javax.swing.JRadioButton();
        btnSup = new controls.JMyBottom();
        btnRecherche = new controls.JMyBottom();
        btnModifier = new controls.JMyBottom();
        btnAjouter = new controls.JMyBottom();
        jLabel1 = new javax.swing.JLabel();
        TextNomU = new controls.JTextBox(20);
        jScrollPane1 = new javax.swing.JScrollPane();
        TblUnité = new javax.swing.JTable();
        btnEffacer = new controls.JMyBottom();
        TextCoefU = new controls.JTextBox(20);
        jLabel2 = new javax.swing.JLabel();
        btnRetoure = new controls.JMyBottom();
        jMyBottom2 = new controls.JMyBottom();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRecherche1 = new controls.JMyBottom();
        RadBtnCoefM = new javax.swing.JRadioButton();
        RadBtnNomM = new javax.swing.JRadioButton();
        RadBtnNumUetr = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        TextRecherche1 = new controls.JTextBox(20);
        btnEffacerM = new controls.JMyBottom();
        btnSupM = new controls.JMyBottom();
        btnModifierM = new controls.JMyBottom();
        btnTrouverM = new controls.JMyBottom();
        btnToutM = new controls.JMyBottom();
        btnAjouterM = new controls.JMyBottom();
        btnRetoureM = new controls.JMyBottom();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextNomM = new controls.JTextBox(20);
        TextCoefM = new controls.JTextBox(20);
        jScrollPane2 = new javax.swing.JScrollPane();
        TblModule = new javax.swing.JTable();
        TextNumUetr = new controls.JMyCombo();
        jMyBottom3 = new controls.JMyBottom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nom :");

        TextNumU.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chercher avec :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("coefficient :");

        RadBtnNum.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnNum.setSelected(true);
        RadBtnNum.setText("Numéro");
        RadBtnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnNumActionPerformed(evt);
            }
        });

        btnTrouver.setText("Trouver");
        btnTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverActionPerformed(evt);
            }
        });

        RadBtnNom.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnNom.setText("Nom");

        btnTout.setText("Tout");
        btnTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutActionPerformed(evt);
            }
        });

        RadBtnCoefU.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnCoefU.setText("coefficient");
        RadBtnCoefU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnCoefUActionPerformed(evt);
            }
        });

        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnRecherche.setText("Rechercher");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 32)); // NOI18N
        jLabel1.setText("Forme Unité");

        TblUnité.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TblUnité.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "coefficient"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUnité.setRowHeight(30);
        TblUnité.setRowMargin(10);
        TblUnité.setSelectionBackground(new java.awt.Color(70, 130, 180));
        TblUnité.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUnitéMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblUnité);

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Numéro :");

        btnRetoure.setText("Retoure");
        btnRetoure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetoureActionPerformed(evt);
            }
        });

        jMyBottom2.setText("Imprimer");
        jMyBottom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextNumU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCoefU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetoure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(RadBtnNum)
                                .addGap(18, 18, 18)
                                .addComponent(RadBtnNom))
                            .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadBtnCoefU)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jMyBottom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnEffacer, btnModifier, btnSup, btnTout, btnTrouver});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRecherche, jMyBottom2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RadBtnNum)
                            .addComponent(RadBtnNom)
                            .addComponent(RadBtnCoefU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyBottom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextNumU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextNomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextCoefU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnRetoure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Unité", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 32)); // NOI18N
        jLabel6.setText("Forme Module");

        btnRecherche1.setText("Rechercher");
        btnRecherche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherche1ActionPerformed(evt);
            }
        });

        RadBtnCoefM.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnCoefM.setText("coefficient");
        RadBtnCoefM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnCoefMActionPerformed(evt);
            }
        });

        RadBtnNomM.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnNomM.setText("Nom");

        RadBtnNumUetr.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnNumUetr.setSelected(true);
        RadBtnNumUetr.setText("Numéro d'unité");
        RadBtnNumUetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnNumUetrActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Chercher avec :");

        btnEffacerM.setText("Effacer");
        btnEffacerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerMActionPerformed(evt);
            }
        });

        btnSupM.setText("Supprimer");
        btnSupM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupMActionPerformed(evt);
            }
        });

        btnModifierM.setText("Modifier");
        btnModifierM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierMActionPerformed(evt);
            }
        });

        btnTrouverM.setText("Trouver");
        btnTrouverM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverMActionPerformed(evt);
            }
        });

        btnToutM.setText("Tout");
        btnToutM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutMActionPerformed(evt);
            }
        });

        btnAjouterM.setText("Ajouter");
        btnAjouterM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterMActionPerformed(evt);
            }
        });

        btnRetoureM.setText("Retoure");
        btnRetoureM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetoureMActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("coefficient :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nom :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Numéro d'unité :");

        TblModule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TblModule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Coefficient", "Numéro d'unité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblModule.setRowHeight(30);
        TblModule.setRowMargin(10);
        TblModule.setSelectionBackground(new java.awt.Color(70, 130, 180));
        TblModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblModuleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblModule);

        TextNumUetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumUetrActionPerformed(evt);
            }
        });

        jMyBottom3.setText("Imprimer");
        jMyBottom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetoureM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAjouterM, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifierM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSupM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnToutM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTrouverM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEffacerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextNomM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCoefM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNumUetr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(TextRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(jMyBottom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(RadBtnNomM)
                            .addGap(18, 18, 18)
                            .addComponent(RadBtnCoefM)
                            .addGap(18, 18, 18)
                            .addComponent(RadBtnNumUetr)
                            .addGap(90, 90, 90)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouterM, btnEffacerM, btnModifierM, btnSupM, btnToutM, btnTrouverM});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRecherche1, jMyBottom3});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(RadBtnNumUetr)
                            .addComponent(RadBtnNomM)
                            .addComponent(RadBtnCoefM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyBottom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TextNomM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TextCoefM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TextNumUetr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSupM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrouverM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToutM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnRetoureM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Module", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setValues(){
    u.setNumU(Integer.parseInt(TextNumU.getText()));
    u.setNomU(TextNomU.getText());
    u.setCoefU(Integer.parseInt(TextCoefU.getText()));
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnGroup.add(RadBtnNum);
        btnGroup.add(RadBtnNom);
        btnGroup.add(RadBtnCoefU);
        btnGroup1.add(RadBtnNomM);
        btnGroup1.add(RadBtnCoefM);
        btnGroup1.add(RadBtnNumUetr);
        u.getAllRows(TblUnité);
        db.go.MyfillCombo("Unité", "NumU", TextNumUetr ,TblUnité.getRowCount());
        Clear();
        ClearM();
        m.getAllRows(TblModule);
                TblModule.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TblModule.getTableHeader().setOpaque(false);
TblModule.getTableHeader().setBackground(new Color(32, 136, 203));
TblModule.getTableHeader().setForeground(new Color(255, 255, 255));
        TblUnité.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TblUnité.getTableHeader().setOpaque(false);
TblUnité.getTableHeader().setBackground(new Color(32, 136, 203));
TblUnité.getTableHeader().setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_formWindowOpened
        Entity.Unité u = new Entity.Unité();
        
    private void Clear(){
    Tools.Tools.ClearTexts(jPanel1);
    TextNumU.setText(u.getAutoNumber());
    btnAjouter.setEnabled(true);
    btnModifier.setEnabled(false);
    btnSup.setEnabled(false);
    TextNomU.requestFocus();
    }
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    private void RadBtnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnNumActionPerformed

    private void btnTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverActionPerformed
        String strNumE = (String) Tools.Tools.InputBox("Entrer le Numéro d'Unité");
        int NumE = Integer.parseInt(strNumE);
        u.setNumU(NumE);
        u.getOneRow(TblUnité);
    }//GEN-LAST:event_btnTrouverActionPerformed

    private void btnToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutActionPerformed
        // TODO add your handling code here:
        u.getAllRows(TblUnité);
    }//GEN-LAST:event_btnToutActionPerformed

    private void RadBtnCoefUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnCoefUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnCoefUActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        if(Tools.Tools.ConfirmMessage("Voulez vous supprimer ? ")){
            setValues();
            u.delete();
            Clear();
            u.getAllRows(TblUnité);}
    }//GEN-LAST:event_btnSupActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        String cherche ="select * from Unité where ";
        if (RadBtnNum.isSelected()){ cherche+="NumU ="+TextRecherche.getText();}
        else if (RadBtnNom.isSelected()){ cherche+="NomU ='"+TextRecherche.getText()+"'";}
        else { cherche+="CoefU ="+TextRecherche.getText()+"";}
        u.getCustomRows(cherche, TblUnité);
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        setValues();
        u.update();
        Clear();
        u.getAllRows(TblUnité);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        setValues();
        u.add();
        Clear();
        u.getAllRows(TblUnité);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void TblUnitéMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUnitéMouseClicked
        try{
            int row = TblUnité.getSelectedRow();
            String NumE = TblUnité.getValueAt(row, 0).toString();
            String NomE = TblUnité.getValueAt(row, 1).toString();
            String CoefU = TblUnité.getValueAt(row, 2).toString();
            TextNumU.setText(NumE);
            TextNomU.setText(NomE);
            TextCoefU.setText(CoefU);
            btnAjouter.setEnabled(false);
            btnModifier.setEnabled(true);
            btnSup.setEnabled(true);
        }catch(Exception ex)
        {Message(ex.getMessage());}
    }//GEN-LAST:event_TblUnitéMouseClicked

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnRetoureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetoureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnRetoureActionPerformed
private void setValuesM(){
    m.setNomM(TextNomM.getText());
    m.setCoefM(Integer.parseInt(TextCoefM.getText()));
    m.setNumE(Integer.parseInt((String) TextNumUetr.getSelectedItem()));
    }
     Module m = new Module();
    private void ClearM(){
    Tools.Tools.ClearTexts(jPanel2);
    btnAjouterM.setEnabled(true);
    btnModifierM.setEnabled(false);
    btnSupM.setEnabled(false);
    TextNomM.requestFocus();
    } 
    private void btnRecherche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherche1ActionPerformed
        // TODO add your handling code here:
        String cherche ="select * from Module where ";
        if (RadBtnNomM.isSelected()){ cherche+="NomM ='"+TextRecherche1.getText()+"'";}
        else if (RadBtnCoefM.isSelected()){ cherche+="CoefM ="+TextRecherche1.getText()+"";}
        else { cherche+="NumU ="+TextRecherche1.getText()+"";}
        m.getCustomRows(cherche, TblModule);
    }//GEN-LAST:event_btnRecherche1ActionPerformed

    private void RadBtnCoefMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnCoefMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnCoefMActionPerformed

    private void RadBtnNumUetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnNumUetrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnNumUetrActionPerformed

    private void btnEffacerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerMActionPerformed
        // TODO add your handling code here:
                ClearM();

    }//GEN-LAST:event_btnEffacerMActionPerformed

    private void btnSupMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupMActionPerformed
        // TODO add your handling code here:
        if(Tools.Tools.ConfirmMessage("Voulez vous supprimer ? ")){
            setValuesM();
            m.delete();
            ClearM();
            m.getAllRows(TblModule);}
    }//GEN-LAST:event_btnSupMActionPerformed

    private void btnModifierMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMActionPerformed
        // TODO add your handling code here:
        setValuesM();
        m.update();
        ClearM();
        m.getAllRows(TblModule);
    }//GEN-LAST:event_btnModifierMActionPerformed

    private void btnTrouverMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverMActionPerformed
        // TODO add your handling code here:
        String strNumE = (String) Tools.Tools.InputBox("Entrer le Nom de Module");
        m.setNomM(strNumE);
        m.getOneRow(TblModule);
    }//GEN-LAST:event_btnTrouverMActionPerformed

    private void btnToutMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutMActionPerformed
        // TODO add your handling code here:
        m.getAllRows(TblModule);
    }//GEN-LAST:event_btnToutMActionPerformed

    private void btnAjouterMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMActionPerformed
        // TODO add your handling code here:
        setValuesM();
        m.add();
        ClearM();
        m.getAllRows(TblModule);
    }//GEN-LAST:event_btnAjouterMActionPerformed

    private void btnRetoureMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetoureMActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnRetoureMActionPerformed

    private void TblModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblModuleMouseClicked
        // TODO add your handling code here:
        try{
            int row = TblModule.getSelectedRow();
            String NomM = TblModule.getValueAt(row, 0).toString();
            String CoefM = TblModule.getValueAt(row, 1).toString();
            String NumU = TblModule.getValueAt(row, 2).toString();
            TextNomM.setText(NomM);
            TextCoefM.setText(CoefM);
            TextNumUetr.setSelectedItem(NumU);
            btnAjouterM.setEnabled(false);
            btnModifierM.setEnabled(true);
            btnSupM.setEnabled(true);
        }catch(Exception ex)
        {Message(ex.getMessage());}
    }//GEN-LAST:event_TblModuleMouseClicked

    private void TextNumUetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumUetrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumUetrActionPerformed

    private void jMyBottom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom2ActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat header = new MessageFormat("Rapport des unités ");
            MessageFormat footer = new MessageFormat("Page - {0}");
            TblUnité.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Message(ex.getMessage());
        }
    }//GEN-LAST:event_jMyBottom2ActionPerformed

    private void jMyBottom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom3ActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat header = new MessageFormat("Rapport des modules ");
            MessageFormat footer = new MessageFormat("Page - {0}");
            TblModule.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Message(ex.getMessage());
        }
    }//GEN-LAST:event_jMyBottom3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unité().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadBtnCoefM;
    private javax.swing.JRadioButton RadBtnCoefU;
    private javax.swing.JRadioButton RadBtnNom;
    private javax.swing.JRadioButton RadBtnNomM;
    private javax.swing.JRadioButton RadBtnNum;
    private javax.swing.JRadioButton RadBtnNumUetr;
    private javax.swing.JTable TblModule;
    private javax.swing.JTable TblUnité;
    private javax.swing.JTextField TextCoefM;
    private javax.swing.JTextField TextCoefU;
    private javax.swing.JTextField TextNomM;
    private javax.swing.JTextField TextNomU;
    private javax.swing.JTextField TextNumU;
    private controls.JMyCombo TextNumUetr;
    private javax.swing.JTextField TextRecherche;
    private javax.swing.JTextField TextRecherche1;
    private controls.JMyBottom btnAjouter;
    private controls.JMyBottom btnAjouterM;
    private controls.JMyBottom btnEffacer;
    private controls.JMyBottom btnEffacerM;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.ButtonGroup btnGroup1;
    private controls.JMyBottom btnModifier;
    private controls.JMyBottom btnModifierM;
    private controls.JMyBottom btnRecherche;
    private controls.JMyBottom btnRecherche1;
    private controls.JMyBottom btnRetoure;
    private controls.JMyBottom btnRetoureM;
    private controls.JMyBottom btnSup;
    private controls.JMyBottom btnSupM;
    private controls.JMyBottom btnTout;
    private controls.JMyBottom btnToutM;
    private controls.JMyBottom btnTrouver;
    private controls.JMyBottom btnTrouverM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private controls.JMyBottom jMyBottom2;
    private controls.JMyBottom jMyBottom3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
